language: node_js

sudo: required

node_js:
  - "7"

cache:
  directories:
    - node_modules
    - $HOME/.npm

notifications:
  email: false

matrix:
  fast_finish: true

env:
  global:
    - SFDX_URL_LINUX=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
    - SFDX_URL_OSX=https://developer.salesforce.com/media/salesforce-cli/sfdx-osx.pkg
    - SFDX_AUTOUPDATE_DISABLE=true
    - SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
    - SFDX_DOMAIN_RETRY=300

os:
  - linux
  - osx

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
      # install CLI
      echo Installing SFDX CLI Linux
      wget -qO- $SFDX_URL_LINUX | tar xJf -
      "./sfdx/install"
      export PATH=./sfdx/$(pwd):$PATH
      sfdx update
    fi
  - |
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      # https://github.com/travis-ci/travis-ci/issues/6307
      rvm get stable
      # install CLI
      echo Installing SFDX CLI macOS
      wget -q $SFDX_URL_OSX
      sudo installer -pkg sfdx-osx.pkg -target /
      sfdx update
    fi
  - |
    # the key should be stored in Travis Repository Setting, wrapped in quotes and newlines replaced with \n
    echo -e $SFDX_CI_DEVHUB_JWTKEY > devhub.key
    sfdx force:auth:jwt:grant --clientid $SFDX_CI_DEVHUB_CLIENTID --username $SFDX_CI_DEVHUB_USERNAME --jwtkeyfile devhub.key --setdefaultdevhubusername --setalias devhub
    rm devhub.key
    curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash

install:
  - npm install
  - npm install -g codecov 

script:
  - npm run compile
  - npm run lint
  - |
    if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      npm run test
    fi
  - |
    if [[ $TRAVIS_OS_NAME == "osx" ]]; then
      # Due to slowness of OS X on Travis
      # https://github.com/travis-ci/travis-ci/issues/6095
      npm run test:without-system-tests
    fi
  - codecov
