name: Apex End to End Tests - Redhat

on:
  workflow_dispatch:
    inputs:
      automationBranch:
        description: 'Set the branch to use for automation tests'
        required: false
        default: 'main'
        type: string
      apexLsp:
        description: 'Apex LSP'
        required: false
        default: true
        type: boolean
      # apexReplayDebugger:
      #   description: 'Apex Replay Debugger'
      #   required: false
      #   default: true
      #   type: boolean
      # debugApexTests:
      #   description: 'Debug Apex Tests'
      #   required: false
      #   default: true
      #   type: boolean
      # runApexTests:
      #   description: 'Run Apex Tests'
      #   required: false
      #   default: true
      #   type: boolean
      # trailApexReplayDebugger:
      #   description: 'Trail Apex Replay Debugger'
      #   required: false
      #   default: true
      #   type: boolean
      vscodeVersion:
        description: 'VSCode Version'
        required: false
        default: 'stable'
        type: string
      runId:
        description: 'Run ID of the workflow run that created the vsixes'
        required: true
        type: string

  workflow_call:
    inputs:
      automationBranch:
        description: 'Set the branch to use for automation tests'
        required: false
        default: 'main'
        type: string
      apexLsp:
        description: 'Apex LSP'
        required: false
        default: true
        type: boolean
      # apexReplayDebugger:
      #   description: 'Apex Replay Debugger'
      #   required: false
      #   default: true
      #   type: boolean
      # debugApexTests:
      #   description: 'Debug Apex Tests'
      #   required: false
      #   default: true
      #   type: boolean
      # runApexTests:
      #   description: 'Run Apex Tests'
      #   required: false
      #   default: true
      #   type: boolean
      # trailApexReplayDebugger:
      #   description: 'Trail Apex Replay Debugger'
      #   required: false
      #   default: true
      #   type: boolean
      vscodeVersion:
        description: 'VSCode Version'
        required: false
        default: 'stable'
        type: string
      runId:
        description: 'Run ID of the workflow run that created the vsixes'
        required: true
        type: string

jobs:
  apexLSP:
    if: ${{ inputs.apexLsp }}
    uses: ./.github/workflows/runE2ETest.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch }}
      automationRepo: 'salesforcedx-vscode-automation-tests-redhat'
      testToRun: 'apexLsp.e2e.js'
      vscodeVersion: ${{ inputs.vscodeVersion }}
      runId: ${{ inputs.runId }}

  # apexReplayDebugger:
  #   if: ${{ inputs.apexReplayDebugger }}
  #   uses: ./.github/workflows/runE2ETest.yml
  #   secrets: inherit
  #   with:
  #     automationBranch: ${{ inputs.automationBranch }}
  #     testToRun: 'apexReplayDebugger.e2e.ts'
  #     vscodeVersion: ${{ inputs.vscodeVersion }}
  #     runId: ${{ inputs.runId }}

  # debugApexTests:
  #   if: ${{ inputs.debugApexTests }}
  #   uses: ./.github/workflows/runE2ETest.yml
  #   secrets: inherit
  #   with:
  #     automationBranch: ${{ inputs.automationBranch }}
  #     testToRun: 'debugApexTests.e2e.ts'
  #     vscodeVersion: ${{ inputs.vscodeVersion }}
  #     runId: ${{ inputs.runId }}

  # runApexTests:
  #   if: ${{ inputs.runApexTests }}
  #   uses: ./.github/workflows/runE2ETest.yml
  #   secrets: inherit
  #   with:
  #     automationBranch: ${{ inputs.automationBranch }}
  #     testToRun: 'runApexTests.e2e.ts'
  #     vscodeVersion: ${{ inputs.vscodeVersion }}
  #     runId: ${{ inputs.runId }}

  # trailApexReplayDebugger:
  #   if: ${{ inputs.trailApexReplayDebugger }}
  #   uses: ./.github/workflows/runE2ETest.yml
  #   secrets: inherit
  #   with:
  #     automationBranch: ${{ inputs.automationBranch }}
  #     testToRun: 'trailApexReplayDebugger.e2e.ts'
  #     vscodeVersion: ${{ inputs.vscodeVersion }}
  #     runId: ${{ inputs.runId }}

  slack_success_notification:
    if: ${{ success() }}
    needs: [apexLSP]
    # needs: [apexLSP, apexReplayDebugger, debugApexTests, runApexTests, trailApexReplayDebugger]
    uses: ./.github/workflows/slackNotification.yml
    secrets: inherit
    with:
      title: 'Apex E2E Tests'
      vscodeVersion: ${{ inputs.vscodeVersion }}
      testsBranch: ${{ inputs.automationBranch }}
      summary: '\n- Apex LSP: ${{ needs.apexLSP.result }}'
      # summary: '\n- Apex LSP: ${{ needs.apexLSP.result }}\n- Apex Replay Debugger: ${{ needs.apexReplayDebugger.result }}\n- Debug Apex Tests: ${{ needs.debugApexTests.result }}\n- Run Apex Tests: ${{ needs.runApexTests.result }}\n- Trail Apex Replay Debugger: ${{ needs.trailApexReplayDebugger.result }}'
      result: 'All the tests passed.'
      workflow: 'actions/runs/${{ github.run_id }}'
      type: 'e2e'

  slack_failure_notification:
    if: ${{ failure() }}
    needs: [apexLSP]
    # needs: [apexLSP, apexReplayDebugger, debugApexTests, runApexTests, trailApexReplayDebugger]
    uses: ./.github/workflows/slackNotification.yml
    secrets: inherit
    with:
      title: 'Apex E2E Tests'
      vscodeVersion: ${{ inputs.vscodeVersion }}
      testsBranch: ${{ inputs.automationBranch }}
      summary: '\n- Apex LSP: ${{ needs.apexLSP.result }}'
      # summary: '\n- Apex LSP: ${{ needs.apexLSP.result }}\n- Apex Replay Debugger: ${{ needs.apexReplayDebugger.result }}\n- Debug Apex Tests: ${{ needs.debugApexTests.result }}\n- Run Apex Tests: ${{ needs.runApexTests.result }}\n- Trail Apex Replay Debugger: ${{ needs.trailApexReplayDebugger.result }}'
      result: 'Not all the tests passed.'
      workflow: 'actions/runs/${{ github.run_id }}'
      type: 'e2e'

  slack_cancelled_notification:
    if: ${{ cancelled() }}
    needs: [apexLSP]
    # needs: [apexLSP, apexReplayDebugger, debugApexTests, runApexTests, trailApexReplayDebugger]
    uses: ./.github/workflows/slackNotification.yml
    secrets: inherit
    with:
      title: 'Apex E2E Tests'
      vscodeVersion: ${{ inputs.vscodeVersion }}
      testsBranch: ${{ inputs.automationBranch }}
      summary: '\n- Apex LSP: ${{ needs.apexLSP.result }}'
      # summary: '\n- Apex LSP: ${{ needs.apexLSP.result }}\n- Apex Replay Debugger: ${{ needs.apexReplayDebugger.result }}\n- Debug Apex Tests: ${{ needs.debugApexTests.result }}\n- Run Apex Tests: ${{ needs.runApexTests.result }}\n- Trail Apex Replay Debugger: ${{ needs.trailApexReplayDebugger.result }}'
      result: 'The workflow was cancelled.'
      workflow: 'actions/runs/${{ github.run_id }}'
      type: 'e2e'
