name: Apex End to End Tests - ESM

on:
  workflow_run:
    workflows:
      - Nightly Build Develop
      - Test, Build, and Release
    types:
      - completed

  workflow_dispatch:
    inputs:
      automationBranch:
        description: 'Set the branch to use for automation tests'
        required: false
        default: 'testesm'
        type: string
      apexLsp:
        description: 'Apex LSP'
        required: false
        default: true
        type: boolean
      apexReplayDebugger:
        description: 'Apex Replay Debugger'
        required: false
        default: true
        type: boolean
      debugApexTests:
        description: 'Debug Apex Tests'
        required: false
        default: true
        type: boolean
      runApexTests:
        description: 'Run Apex Tests'
        required: false
        default: true
        type: boolean
      trailApexReplayDebugger:
        description: 'Trail Apex Replay Debugger'
        required: false
        default: true
        type: boolean
      vscodeVersion:
        description: 'VSCode Version'
        required: false
        default: '1.90.2'
        type: string
      runId:
        description: 'Run ID of the workflow run that created the vsixes'
        required: true
        type: string

  workflow_call:
    inputs:
      automationBranch:
        description: 'Set the branch to use for automation tests'
        required: false
        default: 'testesm'
        type: string
      apexLsp:
        description: 'Apex LSP'
        required: false
        default: true
        type: boolean
      apexReplayDebugger:
        description: 'Apex Replay Debugger'
        required: false
        default: true
        type: boolean
      debugApexTests:
        description: 'Debug Apex Tests'
        required: false
        default: true
        type: boolean
      runApexTests:
        description: 'Run Apex Tests'
        required: false
        default: true
        type: boolean
      trailApexReplayDebugger:
        description: 'Trail Apex Replay Debugger'
        required: false
        default: true
        type: boolean
      vscodeVersion:
        description: 'VSCode Version'
        required: false
        default: '1.90.2'
        type: string
      runId:
        description: 'Run ID of the workflow run that created the vsixes'
        required: true
        type: string

jobs:
  apexLSP:
    if: ${{ inputs.apexLsp || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    uses: ./.github/workflows/runE2ETest.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch || 'testesm' }}
      testToRun: 'apexLsp.e2e.ts'
      vscodeVersion: ${{ inputs.vscodeVersion || '1.90.2' }}
      runId: ${{ inputs.runId || github.event.workflow_run.id  }}
      os: '["macos-latest", "ubuntu-latest"]'

  apexReplayDebugger:
    if: ${{ inputs.apexReplayDebugger || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    uses: ./.github/workflows/runE2ETest.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch || 'testesm' }}
      testToRun: 'apexReplayDebugger.e2e.ts'
      vscodeVersion: ${{ inputs.vscodeVersion || '1.90.2' }}
      runId: ${{ inputs.runId || github.event.workflow_run.id  }}
      os: '["macos-latest", "ubuntu-latest"]'

  debugApexTests:
    if: ${{ inputs.debugApexTests || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    uses: ./.github/workflows/runE2ETest.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch || 'testesm' }}
      testToRun: 'debugApexTests.e2e.ts'
      vscodeVersion: ${{ inputs.vscodeVersion || '1.90.2' }}
      runId: ${{ inputs.runId || github.event.workflow_run.id  }}
      os: '["macos-latest", "ubuntu-latest"]'

  runApexTests:
    if: ${{ inputs.runApexTests || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    uses: ./.github/workflows/runE2ETest.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch || 'testesm' }}
      testToRun: 'runApexTests.e2e.ts'
      vscodeVersion: ${{ inputs.vscodeVersion || '1.90.2' }}
      runId: ${{ inputs.runId || github.event.workflow_run.id  }}
      os: '["macos-latest", "ubuntu-latest"]'

  trailApexReplayDebugger:
    if: ${{ inputs.trailApexReplayDebugger || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    uses: ./.github/workflows/runE2ETest.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch || 'testesm' }}
      testToRun: 'trailApexReplayDebugger.e2e.ts'
      vscodeVersion: ${{ inputs.vscodeVersion || '1.90.2' }}
      runId: ${{ inputs.runId || github.event.workflow_run.id  }}
      os: '["macos-latest", "ubuntu-latest"]'

  slack_success_notification:
    if: ${{ success() }}
    needs:
      [
        apexLSP,
        apexReplayDebugger,
        debugApexTests,
        runApexTests,
        trailApexReplayDebugger
      ]
    uses: ./.github/workflows/slackNotification.yml
    secrets: inherit
    with:
      title: 'Apex E2E Tests - ESM'
      vscodeVersion: ${{ inputs.vscodeVersion || '1.90.2' }}
      testsBranch: ${{ inputs.automationBranch || 'testesm' }}
      summary: '\n- Apex LSP: ${{ needs.apexLSP.result }}\n- Apex Replay Debugger: ${{ needs.apexReplayDebugger.result }}\n- Debug Apex Tests: ${{ needs.debugApexTests.result }}\n- Run Apex Tests: ${{ needs.runApexTests.result }}\n- Trail Apex Replay Debugger: ${{ needs.trailApexReplayDebugger.result }}'
      result: 'All the tests passed.'
      workflow: 'actions/runs/${{ github.run_id }}'
      type: 'e2e'

  slack_failure_notification:
    if: ${{ failure() }}
    needs:
      [
        apexLSP,
        apexReplayDebugger,
        debugApexTests,
        runApexTests,
        trailApexReplayDebugger
      ]
    uses: ./.github/workflows/slackNotification.yml
    secrets: inherit
    with:
      title: 'Apex E2E Tests - ESM'
      vscodeVersion: ${{ inputs.vscodeVersion || '1.90.2' }}
      testsBranch: ${{ inputs.automationBranch || 'testesm' }}
      summary: '\n- Apex LSP: ${{ needs.apexLSP.result }}\n- Apex Replay Debugger: ${{ needs.apexReplayDebugger.result }}\n- Debug Apex Tests: ${{ needs.debugApexTests.result }}\n- Run Apex Tests: ${{ needs.runApexTests.result }}\n- Trail Apex Replay Debugger: ${{ needs.trailApexReplayDebugger.result }}'
      result: 'Not all the tests passed.'
      workflow: 'actions/runs/${{ github.run_id }}'
      type: 'e2e'

  slack_cancelled_notification:
    if: ${{ cancelled() }}
    needs:
      [
        apexLSP,
        apexReplayDebugger,
        debugApexTests,
        runApexTests,
        trailApexReplayDebugger
      ]
    uses: ./.github/workflows/slackNotification.yml
    secrets: inherit
    with:
      title: 'Apex E2E Tests - ESM'
      vscodeVersion: ${{ inputs.vscodeVersion || '1.90.2' }}
      testsBranch: ${{ inputs.automationBranch || 'testesm' }}
      summary: '\n- Apex LSP: ${{ needs.apexLSP.result }}\n- Apex Replay Debugger: ${{ needs.apexReplayDebugger.result }}\n- Debug Apex Tests: ${{ needs.debugApexTests.result }}\n- Run Apex Tests: ${{ needs.runApexTests.result }}\n- Trail Apex Replay Debugger: ${{ needs.trailApexReplayDebugger.result }}'
      result: 'The workflow was cancelled.'
      workflow: 'actions/runs/${{ github.run_id }}'
      type: 'e2e'
