name: E2E Test Suite - ESM

on:
  workflow_run:
    workflows:
      - Nightly Build Develop
      - Test, Build, and Release
    types:
      - completed

  workflow_dispatch:
    inputs:
      automationBranch:
        description: 'Set the branch to use for automation tests'
        required: false
        default: 'testesm'
        type: string
      manifestBuilder:
        description: 'Manifest Builder'
        required: false
        default: true
        type: boolean
      pushAndPull:
        description: 'Push and Pull'
        required: false
        default: true
        type: boolean
      lwcLsp:
        description: 'LWC LSP'
        required: false
        default: true
        type: boolean
      vscodeVersion:
        description: 'VSCode Version'
        required: false
        default: 'stable'
        type: string
      runId:
        description: 'Run ID of the workflow run that created the vsixes'
        required: true
        type: string

  workflow_call:
    inputs:
      automationBranch:
        description: 'Set the branch to use for automation tests'
        required: false
        default: 'testesm'
        type: string
      manifestBuilder:
        description: 'Manifest Builder'
        required: false
        default: true
        type: boolean
      pushAndPull:
        description: 'Push and Pull'
        required: false
        default: true
        type: boolean
      lwcLsp:
        description: 'LWC LSP'
        required: false
        default: true
        type: boolean
      vscodeVersion:
        description: 'VSCode Version'
        required: false
        default: 'stable'
        type: string
      runId:
        description: 'Run ID of the workflow run that created the vsixes'
        required: true
        type: string

jobs:
  manifestBuilder:
    if: ${{ inputs.manifestBuilder || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    uses: ./.github/workflows/runE2ETest.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch || 'testesm' }}
      testToRun: 'manifestBuilder.e2e.ts'
      vscodeVersion: ${{ inputs.vscodeVersion || 'stable' }}
      runId: ${{ inputs.runId || github.event.workflow_run.id  }}
      os: '["macos-latest", "ubuntu-latest", "windows-latest"]'

  pushAndPull:
    if: ${{ inputs.pushAndPull || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    uses: ./.github/workflows/runE2ETest.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch || 'testesm' }}
      testToRun: 'pushAndPull.e2e.ts'
      vscodeVersion: ${{ inputs.vscodeVersion || 'stable' }}
      runId: ${{ inputs.runId || github.event.workflow_run.id  }}
      os: '["macos-latest", "ubuntu-latest", "windows-latest"]'

  lwcLsp:
    if: ${{ inputs.lwcLsp || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    uses: ./.github/workflows/runE2ETest.yml
    secrets: inherit
    with:
      automationBranch: ${{ inputs.automationBranch || 'testesm' }}
      testToRun: 'lwcLsp.e2e.ts'
      vscodeVersion: ${{ inputs.vscodeVersion || 'stable' }}
      runId: ${{ inputs.runId || github.event.workflow_run.id  }}
      os: '["macos-latest", "ubuntu-latest", "windows-latest"]'

  slack_success_notification:
    if: ${{ success() }}
    needs: [manifestBuilder, pushAndPull, lwcLsp]
    uses: ./.github/workflows/slackNotification.yml
    secrets: inherit
    with:
      title: 'E2E Test Suite - ESM'
      vscodeVersion: ${{ inputs.vscodeVersion || 'stable' }}
      testsBranch: ${{ inputs.automationBranch || 'testesm' }}
      summary: '\n- Manifest Builder: ${{ needs.manifestBuilder.result }}\n- Push and Pull: ${{ needs.pushAndPull.result }}\n- LWC LSP: ${{ needs.lwcLsp.result }}'
      result: 'All the tests passed.'
      workflow: 'actions/runs/${{ github.run_id }}'
      type: 'e2e'

  slack_failure_notification:
    if: ${{ failure() }}
    needs: [manifestBuilder, pushAndPull, lwcLsp]
    uses: ./.github/workflows/slackNotification.yml
    secrets: inherit
    with:
      title: 'E2E Test Suite - ESM'
      vscodeVersion: ${{ inputs.vscodeVersion || 'stable' }}
      testsBranch: ${{ inputs.automationBranch || 'testesm' }}
      summary: '\n- Manifest Builder: ${{ needs.manifestBuilder.result }}\n- Push and Pull: ${{ needs.pushAndPull.result }}\n- LWC LSP: ${{ needs.lwcLsp.result }}'
      result: 'Not all the tests passed.'
      workflow: 'actions/runs/${{ github.run_id }}'
      type: 'e2e'

  slack_cancelled_notification:
    if: ${{ cancelled() }}
    needs: [manifestBuilder, pushAndPull, lwcLsp]
    uses: ./.github/workflows/slackNotification.yml
    secrets: inherit
    with:
      title: 'E2E Test Suite - ESM'
      vscodeVersion: ${{ inputs.vscodeVersion || 'stable' }}
      testsBranch: ${{ inputs.automationBranch || 'testesm' }}
      summary: '\n- Manifest Builder: ${{ needs.manifestBuilder.result }}\n- Push and Pull: ${{ needs.pushAndPull.result }}\n- LWC LSP: ${{ needs.lwcLsp.result }}'
      result: 'The workflow was cancelled.'
      workflow: 'actions/runs/${{ github.run_id }}'
      type: 'e2e'
